ml-tooling/contaxy

backend/src/contaxy/api/endpoints/system.py
backend/src/contaxy/managers/system.py

Currently, the /system/initialize endpoint can be called multiple times without authentication. This allows anyone to reset the instance and create an admin account. 
This simple fix checks if there are already users in the DB. If that is the case, the system is not initialized again. This is not perfect, as it does not prevent the usage of the system before initialization is done. Maybe at some point, we could discuss the general idea of this initialization endpoint again.

Ensure /system/initialize endpoint is not called more than once

---

backend/setup.cfg
backend/setup.py
backend/src/contaxy/config.py
backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/file/azure_blob.py
backend/tests/conftest.py
backend/tests/test_file_operations.py

This PR adds the option to use Azure Blob Storage as the object store for Contaxy. The AzureBlobFileManager is implemented as an alternative to the MinioFileManager. It is automatically activated when the `AZURE_BLOB_CONNECTION_STRING` environment variable is set. The access key can either be included in the connection string or it can be specified in the `AZURE_BLOB_TOKEN` variable.
For storing file metadata, the Contaxy PostgresDB is used (similarly to the MinioFileManager). Therefore, the two implementations share a lot of code. It would be possible to extract that logic to reduce the code duplication.
The Azure Blob Storage does not allow the deletion of the currently active file version. Therefore, I had to remove a test case that was trying to only delete the current version. It …

Add support for azure blob storage as object store.

---

backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/docker_utils.py
backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/utils.py

Some service require a token that allows access to the service itself. For example, a [ML workspace](https://github.com/ml-tooling/ml-workspace) service needs this token to build the SSH setup command (the token has to be included in a curl call that downloads the setup script from the workspace).
This PR adds the environment variable CONTAXY_API_TOKEN to each service which includes a token that provides read access to this service. For this, the AuthManager needs to be passed down through several function calls. In the `get_default_environment_variables` function it is then used to generate the token. 
Note:
The user creating the service will be used as the token subject. I don't know if this can cause issue but I think the service itself cannot be a token subject at the moment?

Add API Token to each service/job which allows access to itself

---

backend/src/contaxy/managers/deployment/docker_utils.py
backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/managers/deployment/utils.py

There are some environment variables that are automatically set for a new service. For example the `CONTAXY_DEPLOYMENT_NAME` environment variable which contains the name of the docker container/pod of the service. However, sometimes these values need to be set with a different variable name because the service image can not be adjusted.
An example is the [ml-workspace](https://github.com/ml-tooling/ml-workspace) image. It requires the `SSH_JUMPHOST_TARGET` variable to be set to the hostname of the service. This is exactly the value of the `CONTAXY_DEPLOYMENT_NAME `variable. With the changes in this PR, it is possible to use any default environment variable in the service template syntax:
```
workspace_service_config = ServiceInput(
container_image="mltooling/ml-workspace",
parameters={ …
```

Allow usage of default environment variables in service/job template mappings.

---

backend/src/contaxy/config.py
backend/src/contaxy/managers/deployment/docker_utils.py

This PR fixes two issues:
When HOST_DATA_ROOT_PATH is not set it resulted in volume names with a leading `None` (e.g. `Nonemy-project-pylab-p-my-project-s-test-vol`). 
The validation of the HOST_DATA_ROOT_PATH parameter (must end with slash) was not actually performed as it was not put into a validator method.

Bugfix: Prefix of volume source is None when HOST_DATA_ROOT_PATH is not set

---

backend/src/contaxy/api/dependencies.py
backend/src/contaxy/api/endpoints/user.py
backend/src/contaxy/managers/auth.py

At the moment, even admins cannot create new users when the USER_REGISTRATION_ENABLED variable is set.
To fix this, the get_optional_api_token function is introduced, which tries to retrieve the auth token but does not fail if no token is passed. This can be used in the create_user endpoint to check if the user has admin permissions while still allowing to call the endpoint without any token.

Feature: Allow admins to create users even if self registration is disabled.

---

backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/schema/deployment.py

When a deployment on Kubernetes is deleted, it takes a while for all the pods to be terminated. This PR is adding the "terminating" state which is returned for an ML Lab Service if the deployment was deleted but the pods are still being deleted.

Feature: Add terminating state to service life-cycle

---

backend/src/contaxy/api/endpoints/auth.py
backend/src/contaxy/api/endpoints/user.py
backend/src/contaxy/managers/auth.py
backend/src/contaxy/managers/json_db/postgres.py
backend/src/contaxy/managers/system.py
backend/src/contaxy/schema/system.py

Until now, the contaxy initialization endpoint could only be called as long as no users existed in the DB. As the initialization creates the default admin user, this prevented the initialization to be called more than once. However, a new user could be registered before the initialization was called, which means the initialization could not be done after that.
This PR introduces two main changes:
1. A flag is saved in the DB which indicates whether initialization was already done. To save this flag, a concept of "system properties" was added, which can be used for additional properties of the systems that need to be persisted in the future.
2. All user login and registration endpoints now check if the system is already initialized. If that's not the case, a 403 error response is returned.

Store initialization state in DB and ensure user registration/login is not possible before initialization

---

backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/extension.py
backend/src/contaxy/managers/json_db/postgres.py
backend/src/contaxy/schema/deployment.py
backend/src/contaxy/schema/shared.py
backend/tests/test_deployment_operations.py

At the moment metadata of deployments is only stored directly on the deployed containers/pods (as labels). As a result, this data will be lost once the container/pod is deleted. This PR stores the metadata of each deployment in the internal JSON DB so it is available even if the underlying container/pod was removed.
This provides some advantages:
- Services can be stopped (the underlying container/pod is removed but the deployment is still shown in the UI as stopped)
- Migrations can be easier as only the DB data needs to be transferred
- Features like updating the image of a service can be implemented without the risk of loosing data
This functionality is implemented in a wrapper class `DeploymentManagerWithDB` that builds on top of one of the existing deployment managers (Docker and …

Store deployment metadata in json DB

---

backend/src/contaxy/api/endpoints/deployment.py
backend/src/contaxy/clients/deployment.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/docker_utils.py
backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/deployment/utils.py
backend/src/contaxy/operations/deployment.py
backend/src/contaxy/schema/deployment.py
backend/tests/conftest.py
backend/tests/test_deployment_operations.py

This pull request implements the following features for service deployments in contaxy:
1. The 'wait' query parameter is added to the deploy service endpoint. When it is set to true, the requests waits until the service is deployed (or fails after a 60 second timeout).
2. Add separate command and args field to the deployment class (with the same functionality they have in K8s). This makes it easier to restart services stored in the DB and gives more control over the docker container's ENTRYPOINT and CMD.
3. Add update endpoint for services that allows to change settings like the docker image, compute resources, parameters, etc. This will cause the underlying container to be recreated.
4. Use the service action list/execute endpoints to implement service start, stop and restart. These …

Add functionality for updating, starting, stopping and restarting services

---

backend/src/contaxy/clients/auth.py
backend/src/contaxy/clients/system.py
backend/src/contaxy/managers/auth.py
backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/docker_utils.py
backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/deployment/utils.py
backend/src/contaxy/managers/extension.py
backend/src/contaxy/managers/file/azure_blob.py
backend/src/contaxy/managers/file/minio.py
backend/src/contaxy/managers/project.py
backend/src/contaxy/managers/seed.py
backend/src/contaxy/managers/system.py
backend/src/contaxy/operations/auth.py
backend/src/contaxy/operations/components.py
backend/src/contaxy/operations/system.py
backend/tests/test_auth_operations.py
backend/tests/test_deployment_operations.py
backend/tests/test_file_operations.py
backend/tests/test_project_operations.py
backend/tests/test_system_operations.py
backend/tests/utils.py

The different managers in contaxy (e.g. SystemManager, AuthManager, etc.) need access to other managers. So far, these dependent managers were passed via the constructor directly. 
However, for some of the managers a cyclic dependency can arise. For example the ServiceManager needs the AuthManager to generate self access tokens for newly created services. But at the same time, the AuthManager should use the ServiceManager to update the "last accessed" timestamp of a service when a new session token for that service is generated. To allow this kind of dependency, instead of passing the AuthManager directly to the ServiceManager, instead, the ComponentManager is passed which can be used to retrieve the AuthManager. 
In the constructor of the ServiceManager, the get_auth_manager() function …

Refactor managers to use the ComponentManager to access other managers

---

backend/src/contaxy/api/endpoints/auth.py
backend/src/contaxy/api/endpoints/deployment.py
backend/src/contaxy/clients/deployment.py
backend/src/contaxy/managers/auth.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/operations/deployment.py
backend/src/contaxy/schema/deployment.py
backend/src/contaxy/schema/shared.py
backend/src/contaxy/utils/id_utils.py
backend/tests/test_deployment_operations.py

For some use cases it is required to track the last time a contaxy service was accessed (e.g. automatically stop a service has not been used for a certain time).
This PR adds the properties last_access_time and last_access_user to the Service object that track when the service was last accessed and by which user. These values can be updated via a new endpoint `/projects/{project_id}/services/{service_id}:update-service-access`. Additionally, they are automatically updated if a new session token for a service is requested. As the session tokens are short-lived, this will cause a regular update of the last access time if the service is actively used.

Track last access time and user for all services via session token creation.

---

backend/src/contaxy/managers/auth.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/project.py
backend/tests/test_auth_operations.py
backend/tests/test_deployment_operations.py
backend/tests/test_extensions_operations.py
backend/tests/test_file_operations.py
backend/tests/test_json_db_operations.py
backend/tests/test_project_operations.py

There are some issues that prevented the remote endpoint tests to run successfully on the current code.
Moreover, the remote endpoints left quite a lot of resources (users, projects, services, etc.) on the remote instance. The tests were adjusted to do some more cleanup after each test.

Fix remote endpoint integration tests

---

backend/src/contaxy/api/endpoints/auth.py
backend/src/contaxy/schema/shared.py

At the moment, the contaxy API does not allow to directly view and modify the users permissions. It's only indirectly possible (e.g. adding a user to a project adds the permission for that project).
For extensions or admin users it would be helpful, to have direct access to the user's permissions. Therefore, API endpoints for the following actions should be added:
list permissions of a user
add a new permission to a user
remove a permission from a user
list all users that have a certain permission

Add endpoints for listing, adding and deleting permissions

---

backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/docker_utils.py
backend/src/contaxy/managers/deployment/kube_utils.py
backend/src/contaxy/managers/deployment/kubernetes.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/deployment/utils.py
backend/src/contaxy/managers/extension.py
backend/src/contaxy/operations/deployment.py
backend/src/contaxy/schema/deployment.py
backend/src/contaxy/schema/shared.py
backend/src/contaxy/utils/utils.py
backend/tests/test_deployment_operations.py

This PR continues the refactoring of the deployment manager. 
All service metadata is now always stored in the DB. Additionally the data is still set as labels/annotations on the running containers/pods but these labels are no longer used to reconstruct the metadata when listing the services. 
Only the deployment status and internal id is not stored directly in the DB but is instead always queried during the deployment list/get request and is added dynamically to the response.
This also allows services to be created in a stopped status. That feature can for example be helpful to always create a default workspace for each user in ML Lab but don't have it running by default.

Refactor deployment manager to use DB as source for all service metadata.

---

backend/src/contaxy/managers/auth.py
backend/tests/test_auth_operations.py

When deleting a user, the corresponding entry was deleted from the user db table. However, there are other places (projects, mapping tables, etc.) where the user still existed. 
The deletion process is now extended to delete everything related to the user.

fix user cleanup after user deletion

---

backend/src/contaxy/managers/deployment/docker.py
backend/src/contaxy/managers/deployment/docker_utils.py
backend/tests/test_deployment_operations.py

When deleting a service and requesting the deletion of its volumes via the delete_volumes parameter, the docker container remove API is called like this:
```container.remove(v=delete_volumes)```
From the docs for parameter `v=true`:
> Remove anonymous volumes associated with the container.
This means named volumes are not automatically deleted by this call!
This PR adds the missing logic for deleting all volumes associated with the service if delete_volumes is set to true.
Moreover, some missing imports for docker type definitions were added.

Fix service delation not deleting the named service volume, even if delete_volumes is set to true

---

backend/src/contaxy/api/endpoints/deployment.py
backend/src/contaxy/clients/deployment.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/operations/deployment.py
backend/src/contaxy/schema/shared.py

This PR adds simple support for deployment actions that require parameters.
At the moment it is only used for the stop service action which can receive an optional `delete_volumes` parameter.
In the future this could be extended by listing the available parameters in the list deployment actions endpoint. Then a UI could show a dialog to the user, that allows to set parameters for the deployment action.

Allow passing parameters to deployment actions

---

backend/src/contaxy/api/api.py
backend/src/contaxy/api/dependencies.py
backend/src/contaxy/config.py
backend/src/contaxy/managers/auth.py
backend/src/contaxy/managers/components.py
backend/src/contaxy/managers/deployment/manager.py
backend/src/contaxy/managers/deployment/utils.py
backend/src/contaxy/schema/deployment.py
backend/src/contaxy/utils/fastapi_utils.py

This PR introduces the idle_timeout setting for services. 
If a service is not accessed longer than specified in the idle timeout, it will be automatically stopped.
For computing the idle time, the last_access_time attribute is used. It is updated automatically when a new session token in generated for the service. That way, it is updated regular as long as the service is in use.
A background task is scheduled that will regularly check all services and stops the ones that are over their idle_timeout. Therefore, the services are not guaranteed to be stopped immediately when they pass their idle timeout. Instead, they will be stopped on the next run of the clean up task. The scheduled interval for this clean up task can be set via the `SERVICE_IDLE_CHECK_INTERVAL`.
Moreover, the flag …

Stop services if they have not been accessed for a specified idle timeout

---

backend/src/contaxy/api/endpoints/auth.py
backend/src/contaxy/managers/auth.py

When the user logs in, a new API token in generated and stored as a cookie in the user's browser.
Once the user clicks the log out button this token is removed from the browser's cookies but at the moment it will remain in the backend data base. Because of that, a lot of unused tokens fill up the data base.
This PR add logic to the logout endpoint that removes the token which was used to perform the logout.

Remove user's API token from DB after logout

---

backend/src/contaxy/managers/file/azure_blob.py
backend/src/contaxy/managers/file/minio.py
backend/src/contaxy/schema/file.py
backend/tests/test_file_operations.py

Some fields in the schema for the contaxy file management were marked as optional. That makes it hard to work with, as a check for None need to be done before usage of the field.
For fields that should always have a value, the Optional type has been removed.

Make fields of file schema not optional where None values do not make sense.

---

backend/src/contaxy/api/endpoints/project.py
backend/src/contaxy/api/endpoints/user.py
backend/src/contaxy/managers/file/azure_blob.py
backend/src/contaxy/schema/file.py

So far the project and user token endpoint generate a new token every time. That would cause quite a lot of tokens to be generated over time. 
This PR adds code to check if a user/project token was already created and return that instead of generating a new one.

Improve user and project token endpoints to return same token if it was already generated.

---

backend/src/contaxy/api/endpoints/auth.py
backend/src/contaxy/api/endpoints/user.py
backend/src/contaxy/managers/auth.py
backend/src/contaxy/schema/auth.py

This PR adds tacking of the last activity time of users. 
At the moment, the last activity timestamp is only updated when the users/me endpoint is called (happens on every UI reload). And when a user requests a new session token (happens when the users interacts with a service (e.g. workspace manager)after the session token timeout)

Track last activity of users

---

.github/actions/build-environment/Dockerfile
backend/src/contaxy/api/endpoints/file.py
backend/src/contaxy/clients/file.py
backend/src/contaxy/managers/file/azure_blob.py
backend/src/contaxy/managers/file/minio.py
backend/src/contaxy/operations/file.py
backend/src/contaxy/schema/shared.py
backend/tests/test_file_operations.py

With the commit, we worked the following changes:
1. Ability to store the metadata during file upload -  Now, instead of the corresponding minio S3 bucket storing the metadata, we store it as a Dict in its corresponding Postgre Database entry.

Allow to pass metadata on file upload

---

backend/src/contaxy/schema/shared.py

In this PR, the 'name' attribute is being removed as currently, we are using the 'display_name' attribute to assign names for objects. Hence, accessing the 'name' attribute goes void. To avoid the unnecessary access and usage of the 'name' attribute, it is being removed from the schema.

Removing the 'name' attribute from schema
